name:  testing
on:
  workflow_dispatch
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
           go-version: '1.16.1' 
        - run: go --version
